# -*- coding: utf-8 -*-
"""Tugas6,2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16kpsaBkht5eET-PyUkLyVEIEppqYqsDa
"""

baris = int(input('masukan baris: '))
for i in range(1, baris +1):
     print (i * "*")